### ISSUE TITLE
Unable to resolve "react-native-pbkdf2-shim" from "node_modules/react-native-crypto/index.js"

### ISSUE THREAD

**Issue by kazushige359** [cryptoeconomicslab/automatic#31]
<img width="364" alt="2018-08-25 14 38 05" src="https://user-images.githubusercontent.com/22669833/44615532-1c0d2c00-a877-11e8-8c54-9052a85a174c.png">
I did the following, but it didn't work. 
1. Clear watchman watches.
2. Delete node module folder.
3. Reset metro bundle cache.
4. Remove haste cache. 

Also, I tried to solve this issue based on https://github.com/facebook/react-native/issues/4968, but it doesn't seem to work either...

**Comment by shogochiai** [comment]
Could you try replacing `react-native-crypto` with `crypto-browserify` at package.json and babel-transformer.js

**Comment by kazushige359** [comment]
I think I did, but it doesn't seem to work

**Comment by kazushige359** [comment]
This is another problem, I can't do 'npm start'
<img width="1440" alt="2018-08-25 16 59 33" src="https://user-images.githubusercontent.com/22669833/44616312-9eeab280-a888-11e8-8ca3-5483f410745f.png">

I might downgrade npm based on https://github.com/react-community/create-react-native-app/issues/301

**Comment by shogochiai** [comment]
I believe if you could correctly change crypto module's source from react-native-crypto to crypto-browserify, at least `Unable to resolve "react-native-pbkdf2-shim" from "node_modules/react-native-crypto/index.js"` error won't be shown anymore.

So, I would like to ask to describe how "it doesn't seem to work".

**Comment by kazushige359** [comment]
I deleted react-native-crypto from package.json, removed node modules, and did npm install.

After that,  it gave me this error...
![photo](https://user-images.githubusercontent.com/22669833/44618187-3dd4d600-a8ac-11e8-8b0a-b6802af7a435.jpg)
<img width="356" alt="2018-08-25 21 14 45" src="https://user-images.githubusercontent.com/22669833/44618188-40373000-a8ac-11e8-9199-888c3671610e.png">
